ADULT_THRESHOLD = 65
YOUNG_THRESHOLD = 15
CLEAN_FUELS = ['LPG/cooking gas', 'Biogas', 'Electricity', 1, 5, 14, 16]
CLEAN_FUELS_Zambia = [1, 5, 7, 14]
BUSINESS = ['Contributing family worker', 'Own account worker non-farm', 'Own account worker farm']
CONNECTION = ['National grid', 'Local mini-grid', 'Solar Home System']
NATIONAL_GRID = 'National grid'
LOCAL_MINI_GRID = 'Local mini-grid'
SOLAR_HOME_SYSTEM = 'Solar Home System'
SOLAR_HOME_SYSTEM_SOLAR_PV = 'Solar home system (Solar PV system)'
ALWAYS_HAD_GRID = 'HH has always had grid connection'
